cyclictest: drop unnecessary numa_on_and_available() check
The condition that numa_on_and_available() checks is impossible to hit,
as it's already being checked during process_options().

Removal of numa_on_and_available() also has the side effect of removing
the following warning during build:

src/cyclictest/rt_numa.h:259:15: warning: implicit declaration of function ‘numa_available’ [-Wimplicit-function-declaration]

Signed-off-by: Josh Cartwright <joshc@ni.com>